### ISSUE TITLE
New kill switch domain ...

### ISSUE THREAD

**Issue by franky436** [HIBC2017/WANNAFIX#1]
... this is floating around on twitter, indicating there is at last one new kill switch domain:
https://pbs.twimg.com/media/C_yc8_aWsAAB6wx.jpg:large

**Comment by HIBC2017** [comment]
Hi,

Just added this new kill switch.
Thanks for pointing that out,

Regards,
HIBC

**Comment by franky436** [comment]
One more: https://pbs.twimg.com/media/C_4kyOWXYAMe3Su.jpg:large

**Comment by franky436** [comment]
More: https://pbs.twimg.com/media/C_42tR1WAAA-4-v.jpg:large

**Comment by HIBC2017** [comment]
Hi,

Just updated the source with the new one, just to confirm - it's the same sinkhole in both images?

Regards,
Dan

**Comment by franky436** [comment]
that's true but the last image also shows iuq*ss*.... which should also
be new.

**Comment by HIBC2017** [comment]
Updated, didn't see that - thanks.
