### ISSUE TITLE
Compiler list in readme

### ISSUE THREAD

**Issue by gnubyte** [HIBC2017/WANNAFIX#2]
Any way we could get the optimal compiler in the README for the noobs?

**Comment by HIBC2017** [comment]
Hi,

There shouldn't be a need to compile with _any_ flags.
Are you having issues compiling the code?

Regards,
Dan

**Comment by unprovable** [comment]
I think @gnubyte was just asking what compiler, rather than what flags. 

@gnubyte - it looks like Visual Studio. :)
