### ISSUE TITLE
WANNAFIX.cpp typos

### ISSUE THREAD

**Issue by gnubyte** [HIBC2017/WANNAFIX#5]
Firstly thank you for making this. This is awesome.
While I am a lowly novice, I wanted to raise some bugs.

lines 34 through 37 have no '=' also line 38 terminates in two ;;
 ```
char domaintwo[500]**=**"\n54.153.0.145 ifferfsodp9ifjaposdfjhgosurijfaewrwergwea.com";
        char domainthree[500]**=**"\n207.154.243.152 ayylmaotjhsstasdfasdfasdfasdfasdfasdfasdf.com";
        char domainfour[500]**=**"\n217.182.141.137 iuqssfsodp9ifjaposdfjhgosurijfaewrwergwea.com";
```

Also after entering 'Y' or 'y' to the prompt, I seem to get a type error from scanf when parsing &answer into scanf on line 24 of wannafix.cpp
![Type error](https://cloud.githubusercontent.com/assets/16541000/26078790/a5691288-398e-11e7-9203-a18905e87b0a.png)
Any ideas?

**Comment by HIBC2017** [comment]
Hi,

Thanks for pointing out the typo bugs, I've corrected them!
In regards to the type error, can you elaborate? I can't seem to reproduce the error.

Regards,
Dan
